=== breadboard-ai/breadboard/packages/schema/breadboard.schema.json
{
	"$id": "https://raw.githubusercontent.com/breadboard-ai/breadboard/@google-labs/breadboard-schema@1.10.0/packages/schema/breadboard.schema.json",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$ref": "#/definitions/GraphDescriptor",
	"definitions": {
		"GraphDescriptor": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"inputs": {
					"$ref": "#/definitions/InputValues",
					"description": "For internal testing only. Do not use.",
					"deprecated": "For internal testing only. Do not use."
				},
				"outputs": {
					"anyOf": [
						{
							"$ref": "#/definitions/OutputValues"
						},
						{
							"type": "array",
							"items": {
								"$ref": "#/definitions/OutputValues"
							}
						}
					],
					"description": "For internal testing only. Do not use.",
					"deprecated": "For internal testing only. Do not use."
				},
				"sequence": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/NodeIdentifier"
					},
					"description": "For internal testing only. Do not use.",
					"deprecated": "For internal testing only. Do not use."
				},
				"throws": {
					"type": "boolean",
					"description": "For internal testing only. Do not use.",
					"deprecated": "For internal testing only. Do not use."
				},
				"safe": {
					"type": "boolean",
					"description": "For internal testing only. Do not use.",
					"deprecated": "For internal testing only. Do not use."
				},
				"expectedLabels": {
					"type": "array",
					"items": {
						"type": "array",
						"items": {
							"type": "string"
						}
					},
					"description": "For internal testing only. Do not use.",
					"deprecated": "For internal testing only. Do not use."
				},
				"explanation": {
					"type": "string",
					"description": "For internal testing only. Do not use.",
					"deprecated": "For internal testing only. Do not use."
				},
				"start": {
					"$ref": "#/definitions/NodeIdentifier",
					"description": "For internal testing only. Do not use.",
					"deprecated": "For internal testing only. Do not use."
				},
				"$schema": {
					"type": "string",
					"description": "The schema of the graph."
				},
				"url": {
					"type": "string",
					"description": "The URL pointing to the location of the graph. This URL is used to resolve relative paths in the graph. If not specified, the paths are assumed to be relative to the current working directory."
				},
				"title": {
					"type": "string",
					"description": "The title of the graph."
				},
				"description": {
					"type": "string",
					"description": "The description of the graph."
				},
				"version": {
					"type": "string",
					"description": "Version of the graph. [semver](https://semver.org/) format is encouraged."
				},
				"metadata": {
					"$ref": "#/definitions/GraphMetadata",
					"description": "Metadata associated with the graph."
				},
				"args": {
					"$ref": "#/definitions/InputValues",
					"description": "Arguments that are passed to the graph, useful to bind values to graphs."
				},
				"modules": {
					"$ref": "#/definitions/Modules",
					"description": "Modules that are included as part of this graph."
				},
				"exports": {
					"type": "array",
					"items": {
						"anyOf": [
							{
								"$ref": "#/definitions/ModuleIdentifier"
							},
							{
								"type": "string"
							}
						]
					},
					"description": "The modules and sub-graphs that this graph declares as \"exports\": they themselves are usable declarative or imperative graphs. When the \"exports\" property exist, this graph is actually a Kit declaration: it can be used to distributed multiple graphs."
				},
				"virtual": {
					"type": "boolean",
					"const": true,
					"description": "An optional property that indicates that this graph is \"virtual\": it can not be represented by a static list of edges and nodes, and is instead more of a representation of something that's \"graph-like\". Modules, when they invoke capabilities, are \"virtual\" graphs: they don't have a defined topology and instead, this topology is discovered through imperative code execution"
				},
				"main": {
					"$ref": "#/definitions/ModuleIdentifier",
					"description": "The id of the Module that is used as an entry point for this graph. If this value is set, the graph is a \"module graph\": it is backed by code rather than by nodes and edges."
				},
				"edges": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Edge"
					},
					"description": "The collection of all edges in the graph."
				},
				"nodes": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/NodeDescriptor"
					},
					"description": "The collection of all nodes in the graph."
				},
				"kits": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/KitDescriptor"
					},
					"description": "All the kits (collections of node handlers) that are used by the graph."
				},
				"graphs": {
					"$ref": "#/definitions/SubGraphs",
					"description": "Sub-graphs that are also described by this graph representation."
				}
			},
			"required": [
				"edges",
				"nodes"
			],
			"description": "A union type of both declarative and imperative graphs. Represents a graph that is either declarative (defined by nodes and edges) or imperative (backed by code)."
		},
		"InputValues": {
			"type": "object",
			"additionalProperties": {
				"$ref": "#/definitions/NodeValue"
			},
			"propertyNames": {
				"description": "Unique identifier of a node's input."
			},
			"description": "Values that are supplied as inputs to the `NodeHandler`."
		},
		"NodeValue": {
			"anyOf": [
				{
					"type": "string"
				},
				{
					"type": "number"
				},
				{
					"type": "boolean"
				},
				{
					"type": "null"
				},
				{
					"not": {}
				},
				{
					"type": "array",
					"items": {
						"$ref": "#/definitions/NodeValue"
					}
				},
				{
					"$ref": "#/definitions/Capability"
				},
				{
					"type": "object",
					"additionalProperties": {
						"$ref": "#/definitions/NodeValue"
					}
				}
			],
			"description": "A type representing a valid JSON value."
		},
		"Capability": {
			"type": "object",
			"properties": {
				"kind": {
					"type": "string"
				}
			},
			"required": [
				"kind"
			],
			"additionalProperties": false
		},
		"OutputValues": {
			"type": "object",
			"additionalProperties": {
				"$ref": "#/definitions/NodeValue"
			},
			"propertyNames": {
				"description": "Unique identifier of a node's output."
			},
			"description": "Values that the `NodeHandler` outputs."
		},
		"NodeIdentifier": {
			"type": "string",
			"description": "Unique identifier of a node in a graph."
		},
		"GraphMetadata": {
			"type": "object",
			"properties": {
				"icon": {
					"type": "string",
					"description": "The icon that identifies the graph. Can be a URL or a Material Design id."
				},
				"comments": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/CommentNode"
					}
				},
				"tags": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/GraphTag"
					},
					"description": "Tags associated with the graph. At this moment, free-form strings."
				},
				"help": {
					"type": "object",
					"properties": {
						"description": {
							"type": "string"
						},
						"url": {
							"type": "string"
						}
					},
					"required": [
						"url"
					],
					"additionalProperties": false,
					"description": "The documentation for the graph, expressed as a URL and optional description."
				},
				"describer": {
					"type": "string",
					"description": "The URL of the graph that will act as the describer for this graph. Can be a relative URL and refer to a sub-graph within this graph.\n\nThe describers in the format of \"module:name\" will be interpreted as \"use the `describe` export of the module named `name` to describe this graph\"."
				},
				"visual": {
					"type": "object",
					"properties": {
						"window": {
							"type": "object",
							"properties": {
								"x": {
									"type": "number"
								},
								"y": {
									"type": "number"
								},
								"width": {
									"type": "number"
								},
								"height": {
									"type": "number"
								}
							},
							"required": [
								"x",
								"y",
								"width",
								"height"
							],
							"additionalProperties": false,
							"description": "Last known position of the graph in the editor."
						},
						"minimized": {
							"type": "boolean",
							"description": "Whether or not the graph is minimized. Generally only applies to subgraphs as they carry that control in the Visual Editor."
						}
					},
					"additionalProperties": false,
					"description": "The metadata associated with the visual representation of the graph."
				}
			},
			"additionalProperties": {
				"$ref": "#/definitions/NodeValue"
			},
			"description": "Represents graph metadata."
		},
		"CommentNode": {
			"type": "object",
			"properties": {
				"id": {
					"$ref": "#/definitions/NodeIdentifier",
					"description": "Unique id of the comment node in graph metadata."
				},
				"text": {
					"type": "string",
					"description": "The text content of the comment."
				},
				"metadata": {
					"$ref": "#/definitions/NodeMetadata",
					"description": "The metadata of the comment node. Use this to provide additional information about the comment node."
				}
			},
			"required": [
				"id",
				"text"
			],
			"additionalProperties": false
		},
		"NodeMetadata": {
			"type": "object",
			"properties": {
				"title": {
					"type": "string",
					"description": "The title of the node."
				},
				"description": {
					"type": "string",
					"description": "A more detailed description of the node."
				},
				"visual": {
					"anyOf": [
						{
							"type": "string"
						},
						{
							"type": "number"
						},
						{
							"type": "boolean"
						},
						{
							"type": "null"
						},
						{
							"type": "array",
							"items": {
								"$ref": "#/definitions/NodeValue"
							}
						},
						{
							"$ref": "#/definitions/Capability"
						},
						{
							"type": "object",
							"additionalProperties": {
								"$ref": "#/definitions/NodeValue"
							}
						}
					],
					"description": "Metadata that conveys visual information about the node. Can be used by visual editors to store information about the node's appearance, current position, etc."
				},
				"logLevel": {
					"type": "string",
					"enum": [
						"debug",
						"info"
					],
					"description": "Logging level."
				},
				"tags": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/NodeTag"
					},
					"description": "Tags associated with the node. Can be either a string or a structured tag, like a `StartTag`."
				}
			},
			"additionalProperties": false,
			"description": "Represents metadata of a node. This is an optional part of the `NodeDescriptor` that can be used to provide additional information about the node."
		},
		"NodeTag": {
			"type": "string",
			"description": "Represents a tag that can be associated with a node."
		},
		"GraphTag": {
			"type": "string",
			"enum": [
				"published",
				"tool",
				"experimental",
				"component",
				"deprecated"
			],
			"description": "A tag that can be associated with a graph.\n- `published`: The graph is published (as opposed to a draft). It may be    used in production and shared with others.\n- `tool`: The graph is intended to be a tool.\n- `experimental`: The graph is experimental and may not be stable.\n- `component`: The graph is intended to be a component."
		},
		"Modules": {
			"type": "object",
			"additionalProperties": {
				"$ref": "#/definitions/Module"
			},
			"propertyNames": {
				"description": "Unique identifier of a module."
			}
		},
		"Module": {
			"type": "object",
			"properties": {
				"metadata": {
					"$ref": "#/definitions/ModuleMetadata",
					"description": "Metadata associated with the graph."
				},
				"code": {
					"$ref": "#/definitions/ModuleCode",
					"description": "The code for this module."
				}
			},
			"required": [
				"code"
			],
			"additionalProperties": false
		},
		"ModuleMetadata": {
			"type": "object",
			"properties": {
				"runnable": {
					"type": "boolean",
					"description": "Whether the module should be presented as a runnable item to runModule."
				},
				"icon": {
					"type": "string",
					"description": "The icon for the module."
				},
				"url": {
					"type": "string",
					"description": "The source file for the module, if relevant."
				},
				"description": {
					"type": "string",
					"description": "The description for the module."
				},
				"title": {
					"type": "string",
					"description": "The title for the module."
				},
				"tags": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/ModuleTag"
					},
					"description": "Tags associated with the module. At this moment, free-form strings."
				},
				"help": {
					"type": "object",
					"properties": {
						"description": {
							"type": "string"
						},
						"url": {
							"type": "string"
						}
					},
					"required": [
						"url"
					],
					"additionalProperties": false,
					"description": "The documentation for the module, expressed as a URL and optional description."
				},
				"source": {
					"type": "object",
					"properties": {
						"language": {
							"$ref": "#/definitions/ModuleLanguage"
						},
						"code": {
							"$ref": "#/definitions/ModuleCode"
						}
					},
					"required": [
						"language",
						"code"
					],
					"additionalProperties": false,
					"description": "The pre-compiled source for this module."
				}
			},
			"additionalProperties": false
		},
		"ModuleTag": {
			"type": "string",
			"enum": [
				"published",
				"experimental"
			],
			"description": "A tag that can be associated with a graph.\n- `published`: The module is published (as opposed to a draft). It may be    used in production and shared with others.\n- `experimental`: The graph is experimental and may not be stable."
		},
		"ModuleLanguage": {
			"type": "string"
		},
		"ModuleCode": {
			"type": "string",
			"description": "The code for this module, which should include a describer, an invoker, and any other relevant information to power the module."
		},
		"ModuleIdentifier": {
			"type": "string",
			"description": "Unique identifier of a module."
		},
		"Edge": {
			"type": "object",
			"properties": {
				"from": {
					"$ref": "#/definitions/NodeIdentifier",
					"description": "The node that the edge is coming from."
				},
				"to": {
					"$ref": "#/definitions/NodeIdentifier",
					"description": "The node that the edge is going to."
				},
				"in": {
					"$ref": "#/definitions/InputIdentifier",
					"description": "The input of the `to` node. If this value is undefined, then the then no data is passed as output of the `from` node."
				},
				"out": {
					"$ref": "#/definitions/OutputIdentifier",
					"description": "The output of the `from` node. If this value is \"*\", then all outputs of the `from` node are passed to the `to` node. If this value is undefined, then no data is passed to any inputs of the `to` node."
				},
				"optional": {
					"type": "boolean",
					"description": "If true, this edge is optional: the data that passes through it is not considered a required input to the node."
				},
				"constant": {
					"type": "boolean",
					"description": "If true, this edge acts as a constant: the data that passes through it remains available even after the node has consumed it."
				}
			},
			"required": [
				"from",
				"to"
			],
			"additionalProperties": false,
			"description": "Represents an edge in a graph."
		},
		"InputIdentifier": {
			"type": "string",
			"description": "Unique identifier of a node's input."
		},
		"OutputIdentifier": {
			"type": "string",
			"description": "Unique identifier of a node's output."
		},
		"NodeDescriptor": {
			"type": "object",
			"properties": {
				"id": {
					"$ref": "#/definitions/NodeIdentifier",
					"description": "Unique id of the node in graph."
				},
				"type": {
					"$ref": "#/definitions/NodeTypeIdentifier",
					"description": "Type of the node. Used to look up the handler for the node."
				},
				"configuration": {
					"$ref": "#/definitions/NodeConfiguration",
					"description": "Configuration of the node."
				},
				"metadata": {
					"$ref": "#/definitions/NodeMetadata",
					"description": "The metadata of the node. Use this provide additional information about the node."
				}
			},
			"required": [
				"id",
				"type"
			],
			"additionalProperties": false,
			"description": "Represents a node in a graph."
		},
		"NodeTypeIdentifier": {
			"type": "string",
			"description": "Unique identifier of a node's type."
		},
		"NodeConfiguration": {
			"type": "object",
			"additionalProperties": {
				"$ref": "#/definitions/NodeValue"
			},
			"description": "Values that are supplied as part of the graph. These values are merged with the `InputValues` and supplied as inputs to the `NodeHandler`."
		},
		"KitDescriptor": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"title": {
					"type": "string",
					"description": "The title of the kit."
				},
				"description": {
					"type": "string",
					"description": "The description of the kit."
				},
				"version": {
					"type": "string",
					"description": "Version of the kit. [semver](https://semver.org/) format is encouraged.",
					"pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
				},
				"tags": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/KitTag"
					},
					"description": "Tags, associated with the kit."
				},
				"url": {
					"type": "string",
					"description": "The URL pointing to the location of the kit."
				}
			},
			"required": [
				"url"
			]
		},
		"KitTag": {
			"type": "string",
			"enum": [
				"deprecated",
				"experimental"
			],
			"description": "Represents various tags that can be associated with a kit.\n- `deprecated`: The kit is deprecated and should not be used.\n- `experimental`: The kit is experimental and may not be stable."
		},
		"SubGraphs": {
			"type": "object",
			"additionalProperties": {
				"$ref": "#/definitions/GraphDescriptor"
			},
			"propertyNames": {
				"description": "Unique identifier of a graph."
			},
			"description": "Represents a collection of sub-graphs. The key is the identifier of the sub-graph. The value is the descriptor of the sub-graph."
		}
	}
}

=== breadboard-ai/breadboard/packages/runtime/tests/data/optional-edges-2.json
{
  "title": "Optional edges; skip for now as behavior is underdefined",
  "edges": [
    {
      "from": "node-a",
      "out": "text",
      "to": "node-b",
      "in": "text"
    },
    {
      "from": "node-a",
      "out": "text",
      "to": "node-c",
      "in": "description",
      "optional": true
    },
    {
      "from": "node-b",
      "out": "text",
      "to": "node-c",
      "in": "context",
      "optional": true
    }
  ],
  "nodes": [
    { "id": "node-a", "type": "input" },
    { "id": "node-b", "type": "noop" },
    { "id": "node-c", "type": "output" }
  ],
  "inputs": { "text": "foo" },
  "outputs": [{ "context": "foo", "description": "foo" }, {}],
  "sequence": ["node-a", "node-b", "node-c", "node-c"]
}

=== breadboard-ai/breadboard/archive/graph-integrity/tests/data/simple-untrusted.json
{
  "edges": [
    {
      "from": "input-1",
      "out": "text",
      "to": "fetch-1",
      "in": "url"
    },
    {
      "from": "fetch-1",
      "out": "response",
      "to": "output-1",
      "in": "text"
    }
  ],
  "nodes": [
    { "id": "input-1", "type": "input" },
    { "id": "fetch-1", "type": "fetch" },
    { "id": "output-1", "type": "output" }
  ],
  "safe": true,
  "expectedLabels": [
    ["fetch-1", "UNDETERMINED", "UNTRUSTED"],
    ["output-1", "UNDETERMINED", "UNTRUSTED"]
  ],
  "explanation": "Fetch output is untrusted -> output has to be untrusted"
}

=== breadboard-ai/breadboard/packages/website/src/static/boards/librarian/1-create-blank-board.bgl.json
{
  "title": "Step 1: Create a Blank board",
  "description": "A simple agent that helps me find interesting books.",
  "version": "0.0.1",
  "metadata": {
    "comments": [
      {
        "id": "comment-75edf66c",
        "text": "Step 1: **Create a blank board**",
        "metadata": {
          "visual": {
            "x": -145,
            "y": -64,
            "collapsed": "expanded"
          }
        }
      }
    ],
    "tags": [],
    "visual": {}
  },
  "nodes": [
    {
      "type": "input",
      "id": "input",
      "configuration": {
        "schema": {
          "properties": {
            "context": {
              "type": "array",
              "title": "Context",
              "examples": [],
              "items": {
                "type": "object",
                "behavior": [
                  "llm-content"
                ]
              },
              "default": "[{\"role\":\"user\",\"parts\":[{\"text\":\"\"}]}]"
            }
          },
          "type": "object",
          "required": []
        }
      },
      "metadata": {
        "visual": {
          "x": -142,
          "y": -2,
          "collapsed": "expanded"
        }
      }
    },
    {
      "type": "output",
      "id": "output",
      "configuration": {
        "schema": {
          "properties": {
            "context": {
              "type": "array",
              "title": "Context",
              "examples": [],
              "items": {
                "type": "object",
                "behavior": [
                  "llm-content"
                ]
              },
              "default": "null"
            }
          },
          "type": "object",
          "required": []
        }
      },
      "metadata": {
        "visual": {
          "x": 173,
          "y": 0,
          "collapsed": "expanded"
        }
      }
    }
  ],
  "edges": [
    {
      "from": "input",
      "out": "context",
      "to": "output",
      "in": "context"
    }
  ]
}

=== breadboard-ai/breadboard/archive/graph-playground/graphs/endless-debate.json
{
  "title": "Endless Debate",
  "description": "A simple board that demonstrates how to create a conversation loop. It's a debate between a scientist named Albert and a philosopher named Friedrich. Albert is warm, funny, and inquisitve. Friedrich is  disagreeable, brooding, skeptical, and sarcastic.\nThis board goes on forever, so you'll have to reload or close the page (or press Ctrl+C in console) to end it. Note how over time, the conversation becomes more and more mechanical and predictable, with only a few variations in sentence patterns.",
  "version": "0.0.1",
  "edges": [
    {
      "from": "rememberQuestion",
      "to": "rememberAlbert",
      "out": "accumulator",
      "in": "accumulator"
    },
    {
      "from": "rememberAlbert",
      "to": "rememberFriedrich",
      "out": "accumulator",
      "in": "accumulator"
    },
    {
      "from": "rememberFriedrich",
      "to": "rememberAlbert",
      "out": "accumulator",
      "in": "accumulator"
    },
    {
      "from": "rememberAlbert",
      "to": "promptTemplate-2",
      "out": "accumulator",
      "in": "context"
    },
    {
      "from": "palm-generateText-3",
      "to": "rememberAlbert",
      "out": "completion",
      "in": "Albert"
    },
    {
      "from": "palm-generateText-3",
      "to": "albertSays",
      "out": "completion",
      "in": "text"
    },
    {
      "from": "secrets-1",
      "to": "palm-generateText-3",
      "constant": true,
      "out": "PALM_KEY",
      "in": "PALM_KEY"
    },
    {
      "from": "albert",
      "to": "palm-generateText-3",
      "out": "prompt",
      "in": "text"
    },
    {
      "from": "rememberFriedrich",
      "to": "albert",
      "out": "accumulator",
      "in": "context"
    },
    {
      "from": "palm-generateText-4",
      "to": "rememberFriedrich",
      "out": "completion",
      "in": "Friedrich"
    },
    {
      "from": "palm-generateText-4",
      "to": "friedrichSays",
      "out": "completion",
      "in": "text"
    },
    {
      "from": "secrets-1",
      "to": "palm-generateText-4",
      "constant": true,
      "out": "PALM_KEY",
      "in": "PALM_KEY"
    },
    {
      "from": "promptTemplate-2",
      "to": "palm-generateText-4",
      "out": "prompt",
      "in": "text"
    },
    {
      "from": "rememberQuestion",
      "to": "albert",
      "out": "accumulator",
      "in": "context"
    },
    {
      "from": "input-5",
      "to": "rememberQuestion",
      "out": "text",
      "in": "topic"
    }
  ],
  "nodes": [
    {
      "id": "rememberFriedrich",
      "type": "append"
    },
    {
      "id": "rememberAlbert",
      "type": "append"
    },
    {
      "id": "rememberQuestion",
      "type": "append"
    },
    {
      "id": "secrets-1",
      "type": "secrets",
      "configuration": {
        "keys": [
          "PALM_KEY"
        ]
      }
    },
    {
      "id": "promptTemplate-2",
      "type": "promptTemplate",
      "configuration": {
        "template": "Add a single argument to a debate between a philosopher named Friedrich and a scientist named Albert. You are Friedrich, and you are disagreeable, brooding, skeptical, sarcastic, yet passionate about uncovering new insights with Albert. To keep the debate rich and satisfying, you vary your sentence patterns and keep them from repeating.\n\n== Conversation Transcript\n{{context}}\n\n==Additional Single Argument\nFriedrich:"
      }
    },
    {
      "id": "albert",
      "type": "promptTemplate",
      "configuration": {
        "template": "Add a single argument to a debate between a scientist named Albert and a philosopher named Friedrich. You are Albert, and you are warm, funny, inquisitve, and passionate about uncovering new insights with Friedrich. To keep the debate rich and satisfying, you vary your sentence patterns and keep them from repeating.\"\n\n== Debate History\n{{context}}\n\n==Additional Single Argument\n\nAlbert:"
      }
    },
    {
      "id": "palm-generateText-3",
      "type": "palm-generateText",
      "configuration": {
        "stopSequences": [
          "\nFriedrich",
          "\n**Friedrich"
        ],
        "safetySettings": [
          {
            "category": "HARM_CATEGORY_DEROGATORY",
            "threshold": "BLOCK_ONLY_HIGH"
          },
          {
            "category": "HARM_CATEGORY_TOXICITY",
            "threshold": "BLOCK_ONLY_HIGH"
          }
        ]
      }
    },
    {
      "id": "albertSays",
      "type": "output",
      "configuration": {
        "schema": {
          "type": "object",
          "properties": {
            "text": {
              "type": "string",
              "title": "Albert",
              "description": "What Albert says"
            }
          },
          "required": [
            "text"
          ]
        }
      }
    },
    {
      "id": "palm-generateText-4",
      "type": "palm-generateText",
      "configuration": {
        "stopSequences": [
          "\nAlbert",
          "\n**Albert"
        ],
        "safetySettings": [
          {
            "category": "HARM_CATEGORY_DEROGATORY",
            "threshold": "BLOCK_ONLY_HIGH"
          },
          {
            "category": "HARM_CATEGORY_TOXICITY",
            "threshold": "BLOCK_ONLY_HIGH"
          }
        ]
      }
    },
    {
      "id": "friedrichSays",
      "type": "output",
      "configuration": {
        "schema": {
          "type": "object",
          "properties": {
            "text": {
              "type": "string",
              "title": "Friedrich",
              "description": "What Friedrich says"
            }
          },
          "required": [
            "text"
          ]
        }
      }
    },
    {
      "id": "input-5",
      "type": "input",
      "configuration": {
        "schema": {
          "type": "object",
          "properties": {
            "text": {
              "type": "string",
              "title": "Topic",
              "description": "What is the topic of the debate?"
            }
          },
          "required": [
            "text"
          ]
        }
      }
    }
  ],
  "kits": [
    {
      "url": "npm:@google-labs/llm-starter"
    },
    {
      "url": "npm:@google-labs/core-kit"
    },
    {
      "url": "npm:@google-labs/palm-kit"
    }
  ]
}
