=== breadboard-ai/breadboard/packages/schema/breadboard.schema.json
{
	"$id": "https://raw.githubusercontent.com/breadboard-ai/breadboard/@google-labs/breadboard-schema@1.10.0/packages/schema/breadboard.schema.json",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$ref": "#/definitions/GraphDescriptor",
	"definitions": {
		"GraphDescriptor": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"inputs": {
					"$ref": "#/definitions/InputValues",
					"description": "For internal testing only. Do not use.",
					"deprecated": "For internal testing only. Do not use."
				},
				"outputs": {
					"anyOf": [
						{
							"$ref": "#/definitions/OutputValues"
						},
						{
							"type": "array",
							"items": {
								"$ref": "#/definitions/OutputValues"
							}
						}
					],
					"description": "For internal testing only. Do not use.",
					"deprecated": "For internal testing only. Do not use."
				},
				"sequence": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/NodeIdentifier"
					},
					"description": "For internal testing only. Do not use.",
					"deprecated": "For internal testing only. Do not use."
				},
				"throws": {
					"type": "boolean",
					"description": "For internal testing only. Do not use.",
					"deprecated": "For internal testing only. Do not use."
				},
				"safe": {
					"type": "boolean",
					"description": "For internal testing only. Do not use.",
					"deprecated": "For internal testing only. Do not use."
				},
				"expectedLabels": {
					"type": "array",
					"items": {
						"type": "array",
						"items": {
							"type": "string"
						}
					},
					"description": "For internal testing only. Do not use.",
					"deprecated": "For internal testing only. Do not use."
				},
				"explanation": {
					"type": "string",
					"description": "For internal testing only. Do not use.",
					"deprecated": "For internal testing only. Do not use."
				},
				"start": {
					"$ref": "#/definitions/NodeIdentifier",
					"description": "For internal testing only. Do not use.",
					"deprecated": "For internal testing only. Do not use."
				},
				"$schema": {
					"type": "string",
					"description": "The schema of the graph."
				},
				"url": {
					"type": "string",
					"description": "The URL pointing to the location of the graph. This URL is used to resolve relative paths in the graph. If not specified, the paths are assumed to be relative to the current working directory."
				},
				"title": {
					"type": "string",
					"description": "The title of the graph."
				},
				"description": {
					"type": "string",
					"description": "The description of the graph."
				},
				"version": {
					"type": "string",
					"description": "Version of the graph. [semver](https://semver.org/) format is encouraged."
				},
				"metadata": {
					"$ref": "#/definitions/GraphMetadata",
					"description": "Metadata associated with the graph."
				},
				"args": {
					"$ref": "#/definitions/InputValues",
					"description": "Arguments that are passed to the graph, useful to bind values to graphs."
				},
				"modules": {
					"$ref": "#/definitions/Modules",
					"description": "Modules that are included as part of this graph."
				},
				"exports": {
					"type": "array",
					"items": {
						"anyOf": [
							{
								"$ref": "#/definitions/ModuleIdentifier"
							},
							{
								"type": "string"
							}
						]
					},
					"description": "The modules and sub-graphs that this graph declares as \"exports\": they themselves are usable declarative or imperative graphs. When the \"exports\" property exist, this graph is actually a Kit declaration: it can be used to distributed multiple graphs."
				},
				"virtual": {
					"type": "boolean",
					"const": true,
					"description": "An optional property that indicates that this graph is \"virtual\": it can not be represented by a static list of edges and nodes, and is instead more of a representation of something that's \"graph-like\". Modules, when they invoke capabilities, are \"virtual\" graphs: they don't have a defined topology and instead, this topology is discovered through imperative code execution"
				},
				"main": {
					"$ref": "#/definitions/ModuleIdentifier",
					"description": "The id of the Module that is used as an entry point for this graph. If this value is set, the graph is a \"module graph\": it is backed by code rather than by nodes and edges."
				},
				"edges": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Edge"
					},
					"description": "The collection of all edges in the graph."
				},
				"nodes": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/NodeDescriptor"
					},
					"description": "The collection of all nodes in the graph."
				},
				"kits": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/KitDescriptor"
					},
					"description": "All the kits (collections of node handlers) that are used by the graph."
				},
				"graphs": {
					"$ref": "#/definitions/SubGraphs",
					"description": "Sub-graphs that are also described by this graph representation."
				}
			},
			"required": [
				"edges",
				"nodes"
			],
			"description": "A union type of both declarative and imperative graphs. Represents a graph that is either declarative (defined by nodes and edges) or imperative (backed by code)."
		},
		"InputValues": {
			"type": "object",
			"additionalProperties": {
				"$ref": "#/definitions/NodeValue"
			},
			"propertyNames": {
				"description": "Unique identifier of a node's input."
			},
			"description": "Values that are supplied as inputs to the `NodeHandler`."
		},
		"NodeValue": {
			"anyOf": [
				{
					"type": "string"
				},
				{
					"type": "number"
				},
				{
					"type": "boolean"
				},
				{
					"type": "null"
				},
				{
					"not": {}
				},
				{
					"type": "array",
					"items": {
						"$ref": "#/definitions/NodeValue"
					}
				},
				{
					"$ref": "#/definitions/Capability"
				},
				{
					"type": "object",
					"additionalProperties": {
						"$ref": "#/definitions/NodeValue"
					}
				}
			],
			"description": "A type representing a valid JSON value."
		},
		"Capability": {
			"type": "object",
			"properties": {
				"kind": {
					"type": "string"
				}
			},
			"required": [
				"kind"
			],
			"additionalProperties": false
		},
		"OutputValues": {
			"type": "object",
			"additionalProperties": {
				"$ref": "#/definitions/NodeValue"
			},
			"propertyNames": {
				"description": "Unique identifier of a node's output."
			},
			"description": "Values that the `NodeHandler` outputs."
		},
		"NodeIdentifier": {
			"type": "string",
			"description": "Unique identifier of a node in a graph."
		},
		"GraphMetadata": {
			"type": "object",
			"properties": {
				"icon": {
					"type": "string",
					"description": "The icon that identifies the graph. Can be a URL or a Material Design id."
				},
				"comments": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/CommentNode"
					}
				},
				"tags": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/GraphTag"
					},
					"description": "Tags associated with the graph. At this moment, free-form strings."
				},
				"help": {
					"type": "object",
					"properties": {
						"description": {
							"type": "string"
						},
						"url": {
							"type": "string"
						}
					},
					"required": [
						"url"
					],
					"additionalProperties": false,
					"description": "The documentation for the graph, expressed as a URL and optional description."
				},
				"describer": {
					"type": "string",
					"description": "The URL of the graph that will act as the describer for this graph. Can be a relative URL and refer to a sub-graph within this graph.\n\nThe describers in the format of \"module:name\" will be interpreted as \"use the `describe` export of the module named `name` to describe this graph\"."
				},
				"visual": {
					"type": "object",
					"properties": {
						"window": {
							"type": "object",
							"properties": {
								"x": {
									"type": "number"
								},
								"y": {
									"type": "number"
								},
								"width": {
									"type": "number"
								},
								"height": {
									"type": "number"
								}
							},
							"required": [
								"x",
								"y",
								"width",
								"height"
							],
							"additionalProperties": false,
							"description": "Last known position of the graph in the editor."
						},
						"minimized": {
							"type": "boolean",
							"description": "Whether or not the graph is minimized. Generally only applies to subgraphs as they carry that control in the Visual Editor."
						}
					},
					"additionalProperties": false,
					"description": "The metadata associated with the visual representation of the graph."
				}
			},
			"additionalProperties": {
				"$ref": "#/definitions/NodeValue"
			},
			"description": "Represents graph metadata."
		},
		"CommentNode": {
			"type": "object",
			"properties": {
				"id": {
					"$ref": "#/definitions/NodeIdentifier",
					"description": "Unique id of the comment node in graph metadata."
				},
				"text": {
					"type": "string",
					"description": "The text content of the comment."
				},
				"metadata": {
					"$ref": "#/definitions/NodeMetadata",
					"description": "The metadata of the comment node. Use this to provide additional information about the comment node."
				}
			},
			"required": [
				"id",
				"text"
			],
			"additionalProperties": false
		},
		"NodeMetadata": {
			"type": "object",
			"properties": {
				"title": {
					"type": "string",
					"description": "The title of the node."
				},
				"description": {
					"type": "string",
					"description": "A more detailed description of the node."
				},
				"visual": {
					"anyOf": [
						{
							"type": "string"
						},
						{
							"type": "number"
						},
						{
							"type": "boolean"
						},
						{
							"type": "null"
						},
						{
							"type": "array",
							"items": {
								"$ref": "#/definitions/NodeValue"
							}
						},
						{
							"$ref": "#/definitions/Capability"
						},
						{
							"type": "object",
							"additionalProperties": {
								"$ref": "#/definitions/NodeValue"
							}
						}
					],
					"description": "Metadata that conveys visual information about the node. Can be used by visual editors to store information about the node's appearance, current position, etc."
				},
				"logLevel": {
					"type": "string",
					"enum": [
						"debug",
						"info"
					],
					"description": "Logging level."
				},
				"tags": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/NodeTag"
					},
					"description": "Tags associated with the node. Can be either a string or a structured tag, like a `StartTag`."
				}
			},
			"additionalProperties": false,
			"description": "Represents metadata of a node. This is an optional part of the `NodeDescriptor` that can be used to provide additional information about the node."
		},
		"NodeTag": {
			"type": "string",
			"description": "Represents a tag that can be associated with a node."
		},
		"GraphTag": {
			"type": "string",
			"enum": [
				"published",
				"tool",
				"experimental",
				"component",
				"deprecated"
			],
			"description": "A tag that can be associated with a graph.\n- `published`: The graph is published (as opposed to a draft). It may be    used in production and shared with others.\n- `tool`: The graph is intended to be a tool.\n- `experimental`: The graph is experimental and may not be stable.\n- `component`: The graph is intended to be a component."
		},
		"Modules": {
			"type": "object",
			"additionalProperties": {
				"$ref": "#/definitions/Module"
			},
			"propertyNames": {
				"description": "Unique identifier of a module."
			}
		},
		"Module": {
			"type": "object",
			"properties": {
				"metadata": {
					"$ref": "#/definitions/ModuleMetadata",
					"description": "Metadata associated with the graph."
				},
				"code": {
					"$ref": "#/definitions/ModuleCode",
					"description": "The code for this module."
				}
			},
			"required": [
				"code"
			],
			"additionalProperties": false
		},
		"ModuleMetadata": {
			"type": "object",
			"properties": {
				"runnable": {
					"type": "boolean",
					"description": "Whether the module should be presented as a runnable item to runModule."
				},
				"icon": {
					"type": "string",
					"description": "The icon for the module."
				},
				"url": {
					"type": "string",
					"description": "The source file for the module, if relevant."
				},
				"description": {
					"type": "string",
					"description": "The description for the module."
				},
				"title": {
					"type": "string",
					"description": "The title for the module."
				},
				"tags": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/ModuleTag"
					},
					"description": "Tags associated with the module. At this moment, free-form strings."
				},
				"help": {
					"type": "object",
					"properties": {
						"description": {
							"type": "string"
						},
						"url": {
							"type": "string"
						}
					},
					"required": [
						"url"
					],
					"additionalProperties": false,
					"description": "The documentation for the module, expressed as a URL and optional description."
				},
				"source": {
					"type": "object",
					"properties": {
						"language": {
							"$ref": "#/definitions/ModuleLanguage"
						},
						"code": {
							"$ref": "#/definitions/ModuleCode"
						}
					},
					"required": [
						"language",
						"code"
					],
					"additionalProperties": false,
					"description": "The pre-compiled source for this module."
				}
			},
			"additionalProperties": false
		},
		"ModuleTag": {
			"type": "string",
			"enum": [
				"published",
				"experimental"
			],
			"description": "A tag that can be associated with a graph.\n- `published`: The module is published (as opposed to a draft). It may be    used in production and shared with others.\n- `experimental`: The graph is experimental and may not be stable."
		},
		"ModuleLanguage": {
			"type": "string"
		},
		"ModuleCode": {
			"type": "string",
			"description": "The code for this module, which should include a describer, an invoker, and any other relevant information to power the module."
		},
		"ModuleIdentifier": {
			"type": "string",
			"description": "Unique identifier of a module."
		},
		"Edge": {
			"type": "object",
			"properties": {
				"from": {
					"$ref": "#/definitions/NodeIdentifier",
					"description": "The node that the edge is coming from."
				},
				"to": {
					"$ref": "#/definitions/NodeIdentifier",
					"description": "The node that the edge is going to."
				},
				"in": {
					"$ref": "#/definitions/InputIdentifier",
					"description": "The input of the `to` node. If this value is undefined, then the then no data is passed as output of the `from` node."
				},
				"out": {
					"$ref": "#/definitions/OutputIdentifier",
					"description": "The output of the `from` node. If this value is \"*\", then all outputs of the `from` node are passed to the `to` node. If this value is undefined, then no data is passed to any inputs of the `to` node."
				},
				"optional": {
					"type": "boolean",
					"description": "If true, this edge is optional: the data that passes through it is not considered a required input to the node."
				},
				"constant": {
					"type": "boolean",
					"description": "If true, this edge acts as a constant: the data that passes through it remains available even after the node has consumed it."
				}
			},
			"required": [
				"from",
				"to"
			],
			"additionalProperties": false,
			"description": "Represents an edge in a graph."
		},
		"InputIdentifier": {
			"type": "string",
			"description": "Unique identifier of a node's input."
		},
		"OutputIdentifier": {
			"type": "string",
			"description": "Unique identifier of a node's output."
		},
		"NodeDescriptor": {
			"type": "object",
			"properties": {
				"id": {
					"$ref": "#/definitions/NodeIdentifier",
					"description": "Unique id of the node in graph."
				},
				"type": {
					"$ref": "#/definitions/NodeTypeIdentifier",
					"description": "Type of the node. Used to look up the handler for the node."
				},
				"configuration": {
					"$ref": "#/definitions/NodeConfiguration",
					"description": "Configuration of the node."
				},
				"metadata": {
					"$ref": "#/definitions/NodeMetadata",
					"description": "The metadata of the node. Use this provide additional information about the node."
				}
			},
			"required": [
				"id",
				"type"
			],
			"additionalProperties": false,
			"description": "Represents a node in a graph."
		},
		"NodeTypeIdentifier": {
			"type": "string",
			"description": "Unique identifier of a node's type."
		},
		"NodeConfiguration": {
			"type": "object",
			"additionalProperties": {
				"$ref": "#/definitions/NodeValue"
			},
			"description": "Values that are supplied as part of the graph. These values are merged with the `InputValues` and supplied as inputs to the `NodeHandler`."
		},
		"KitDescriptor": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"title": {
					"type": "string",
					"description": "The title of the kit."
				},
				"description": {
					"type": "string",
					"description": "The description of the kit."
				},
				"version": {
					"type": "string",
					"description": "Version of the kit. [semver](https://semver.org/) format is encouraged.",
					"pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
				},
				"tags": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/KitTag"
					},
					"description": "Tags, associated with the kit."
				},
				"url": {
					"type": "string",
					"description": "The URL pointing to the location of the kit."
				}
			},
			"required": [
				"url"
			]
		},
		"KitTag": {
			"type": "string",
			"enum": [
				"deprecated",
				"experimental"
			],
			"description": "Represents various tags that can be associated with a kit.\n- `deprecated`: The kit is deprecated and should not be used.\n- `experimental`: The kit is experimental and may not be stable."
		},
		"SubGraphs": {
			"type": "object",
			"additionalProperties": {
				"$ref": "#/definitions/GraphDescriptor"
			},
			"propertyNames": {
				"description": "Unique identifier of a graph."
			},
			"description": "Represents a collection of sub-graphs. The key is the identifier of the sub-graph. The value is the descriptor of the sub-graph."
		}
	}
}

=== breadboard-ai/breadboard/packages/breadboard-web/public/graphs/team-builder.json
{
  "title": "Team Builder",
  "description": "Build a team of experts",
  "version": "0.0.1",
  "edges": [
    {
      "from": "jobDescriptions",
      "to": "output-2",
      "out": "json",
      "in": "text"
    },
    {
      "from": "input-1",
      "to": "jobDescriptionsPrompt",
      "out": "purpose",
      "in": "purpose"
    },
    {
      "from": "input-1",
      "to": "jobDescriptions",
      "out": "generator",
      "in": "generator"
    },
    {
      "from": "jobDescriptionsPrompt",
      "to": "jobDescriptions",
      "out": "prompt",
      "in": "text"
    }
  ],
  "nodes": [
    {
      "id": "output-2",
      "type": "output",
      "configuration": {
        "schema": {
          "type": "object",
          "properties": {
            "text": {
              "type": "string",
              "title": "text"
            }
          },
          "required": [
            "text"
          ]
        }
      }
    },
    {
      "id": "jobDescriptions",
      "type": "invoke",
      "configuration": {
        "path": "json-agent.json",
        "schema": {
          "type": "object",
          "properties": {
            "descriptions": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "title": {
                    "type": "string",
                    "description": "expert's title"
                  },
                  "responsibilities": {
                    "type": "array",
                    "items": {
                      "type": "string",
                      "description": "expert's responsibilities"
                    }
                  }
                }
              }
            }
          }
        },
        "context": []
      }
    },
    {
      "id": "input-1",
      "type": "input",
      "configuration": {
        "schema": {
          "type": "object",
          "properties": {
            "purpose": {
              "title": "Purpose",
              "description": "The value to substitute for the parameter \"purpose\"",
              "type": [
                "string",
                "object"
              ],
              "examples": [
                "Create high quality rhyming poems that will be used as lyrics for jingles in TV commercials. Creating melodies and producing music is not part of job."
              ],
              "format": "multiline"
            },
            "generator": {
              "title": "Generator",
              "examples": [
                "gemini-generator.json"
              ],
              "type": "string"
            }
          },
          "required": [
            "purpose",
            "generator"
          ]
        }
      }
    },
    {
      "id": "jobDescriptionsPrompt",
      "type": "promptTemplate",
      "configuration": {
        "template": "You are building a team of expert LLM-based agents for the following purpose:\n      \n{{purpose}}\n\nThese expert agents can only read text and produce text. The experts will work as a team, collaborating, creating, reviewing, critiquing, and iteratively improving the quality of the poems.\n\nPlease identify the necessary job descriptions of these experts."
      }
    }
  ],
  "graphs": {}
}

=== breadboard-ai/breadboard/packages/agent-kit/boards/looper.json
{
  "title": "Looper",
  "description": "A worker whose job it is to repeat the same thing over and over, until some condition is met or the max count of repetitions is reached.",
  "$schema": "https://raw.githubusercontent.com/breadboard-ai/breadboard/@google-labs/breadboard-schema@1.4.1/packages/schema/breadboard.schema.json",
  "version": "0.0.1",
  "edges": [
    {
      "from": "fn-3",
      "to": "output-2",
      "out": "stop",
      "in": "context"
    },
    {
      "from": "input-1",
      "to": "fn-3",
      "out": "context",
      "in": "context"
    },
    {
      "from": "input-1",
      "to": "fn-3",
      "out": "plan",
      "in": "count"
    }
  ],
  "nodes": [
    {
      "id": "output-2",
      "type": "output",
      "configuration": {
        "schema": {
          "type": "object",
          "properties": {
            "context": {
              "type": "array",
              "items": {
                "type": "object",
                "behavior": [
                  "llm-content"
                ]
              },
              "title": "Done"
            }
          }
        }
      }
    },
    {
      "id": "fn-3",
      "type": "runJavascript",
      "configuration": {
        "code": "const fn_3 = ({ context, count }) => {\n  const num = count - 1;\n  if (num != 0) {\n    return { continue: context, count: num };\n  }\n  return { stop: context };\n};",
        "name": "fn_3",
        "raw": true
      },
      "metadata": {
        "title": "Count Iteration"
      }
    },
    {
      "id": "input-1",
      "type": "input",
      "configuration": {
        "schema": {
          "type": "object",
          "properties": {
            "context": {
              "title": "Context in",
              "type": "array",
              "items": {
                "type": "object",
                "behavior": [
                  "llm-content"
                ]
              },
              "default": "[]",
              "description": "Initial conversation context"
            },
            "plan": {
              "title": "Plan",
              "description": "For now, the maximum number of repetitions to make (set to -1 to go infinitely)",
              "type": "object",
              "default": "{\"max\":0}",
              "examples": [
                "{\"max\":1}"
              ]
            }
          },
          "required": []
        }
      }
    }
  ],
  "kits": [],
  "graphs": {}
}

=== breadboard-ai/breadboard/packages/breadboard/tests/data/valid-start-node.json
{
  "edges": [
    {
      "from": "node-b",
      "out": "text",
      "to": "node-c",
      "in": "data"
    },
    {
      "from": "node-a",
      "out": "text",
      "to": "node-d",
      "in": "data"
    }
  ],
  "nodes": [
    { "id": "node-a", "type": "input" },
    {
      "id": "node-b",
      "type": "input"
    },
    { "id": "node-c", "type": "output" },
    { "id": "node-d", "type": "output" }
  ],
  "inputs": { "text": "foo" },
  "outputs": [{ "data": "foo" }],
  "sequence": ["node-b", "node-c"],
  "start": "node-b"
}
